context:
  name: cargo-zigbuild
  version: "0.22.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/rust-cross/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5e47aedd4d77eee92995a0a9e9aaa945c3f75e502ac5a1f624c111bdbf87b129

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
  run:
    - zig >=0.9.0

tests:
  - script: cargo-zigbuild --help

about:
  homepage: https://github.com/rust-cross/cargo-zigbuild
  summary: 'Compile Cargo project with zig as linker'
  description: |
    Compile Cargo project with zig as linker for easier cross compiling.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/rust-cross/cargo-zigbuild

extra:
  recipe-maintainers:
    - ruben-arts
    - messense
